=== matysbrule/SNIR2_2022_2023/Cours XML/TD XML/public_html/ordinateur.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/emptyDTD.dtd to edit this template
-->

<!--
    TODO define vocabulary identification data
    PUBLIC ID  : -//vendor//vocabulary//EN
    SYSTEM ID  : http://server/path/__NAME__
-->

<!-- TODO define your own vocabulary/syntax. Example follows:  -->
<!ELEMENT ordinateur (boitier+)>
<!ELEMENT boitier (cartmere*,cartegraphique*,processeur*,ram*)>
<!ELEMENT cartemÃ¨re (cartegraphique*,processeur*,ram*)>
<!ELEMENT cartegraphique (marque?,modele?)>
<!ELEMENT processeur (marque?,modele?)>
<!ELEMENT ram (marque?,modele?)>
<!ELEMENT marque (#PCDATA)>
<!ELEMENT modele (#PCDATA)>

=== matysbrule/SNIR2_2022_2023/Cours XML/TD XML/public_html/ordinateur.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XMLDocument.xml to edit this template
-->

<!DOCTYPE ordinateur SYSTEM 'ordinateur.dtd'>


<ordinateur>
    <boitier>
        <cartemere>
            <marque>Asus</marque>
            <modele>Z690</modele>
        </cartemere>
        <cartegraphique>
            <marque>Nvidia</marque>
            <modele>1080ti</modele>
            <ram>
                <marque>Crucial</marque>
                <modele>Ballistix BL2K8G36C16U4W</modele>
                
            </ram>
        </cartegraphique>
        
        
        
        
    </boitier>
    
</ordinateur>
